name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  my_job:
    name: CHROOT UPDATE DEBIAN 
    runs-on: ubuntu-latest

    steps:
    - name: CHROOT INSTALL DEBIAN
      shell: bash
      run: |
       CROSS_ROOT="/mnt/chroot-debian"
       CROSS_MIRROR="http://deb.debian.org/debian/"
       
       sudo apt-get -y install debootstrap -y

       sudo mkdir -p $CROSS_ROOT
       sudo debootstrap --arch=amd64 stable $CROSS_ROOT $CROSS_MIRROR
       
       sudo mount -t proc /proc $CROSS_ROOT/proc
       sudo mount -t sysfs /sys $CROSS_ROOT/sys
       sudo mount --bind /dev $CROSS_ROOT/dev
       sudo mount --bind /dev/pts $CROSS_ROOT/dev/pts

       sudo chroot $CROSS_ROOT /bin/bash

    - name: debian apt-get update
      shell: bash
      run: |
       CROSS_ROOT="/mnt/chroot-debian"

       sudo chroot $CROSS_ROOT /bin/bash -c "
        apt-get update && apt-get install nginx dropbear-initramfs strongswan strongswan-pki -y"